from django.core.management.base import BaseCommand
from django.db import transaction
from django.apps import apps


class Command(BaseCommand):
    help = "Seed the database with initial Categories, Rarities, Biomes, Reagents, and PotionEffects."

    def add_arguments(self, parser):
        parser.add_argument(
            "--flush",
            action="store_true",
            help="Delete existing seeded data before seeding (DEV ONLY).",
        )

    @transaction.atomic
    def handle(self, *args, **options):
        Category = apps.get_model("alchemist", "Category")
        Rarity = apps.get_model("alchemist", "Rarity")
        Reagent = apps.get_model("alchemist", "Reagent")
        Biome = apps.get_model("alchemist", "Biome")
        PotionEffect = apps.get_model("alchemist", "PotionEffect")

        if options["flush"]:
            self.stdout.write(self.style.WARNING("⚠️  Flushing tables..."))
            PotionEffect.objects.all().delete()
            Biome.objects.all().delete()
            Reagent.objects.all().delete()
            Category.objects.all().delete()
            Rarity.objects.all().delete()

        # -------------------------
        # 0) Categories + Rarities
        # -------------------------
        category_seed = [
            {"name": "Plant", "uses_cluster_dice": True},
            {"name": "Animal", "uses_cluster_dice": True},
            {"name": "Mineral", "uses_cluster_dice": True},
            {"name": "Carve", "uses_cluster_dice": False},
            {"name": "Other", "uses_cluster_dice": True},
        ]

        categories_by_name = {}
        for c in category_seed:
            obj, created = Category.objects.update_or_create(
                name=c["name"],
                defaults={"uses_cluster_dice": c["uses_cluster_dice"]},
            )
            categories_by_name[obj.name] = obj
            self.stdout.write(f"{'➕' if created else '✔️'} Category: {obj.name}")

        rarity_seed = [
            {"name": "Common"},
            {"name": "Uncommon"},
            {"name": "Rare"}
        ]

        rarities_by_name = {}
        for r in rarity_seed:
            obj, created = Rarity.objects.update_or_create(name=r["name"], defaults={})
            rarities_by_name[obj.name] = obj
            self.stdout.write(f"{'➕' if created else '✔️'} Rarity: {obj.name}")

        # -------------------------
        # 1) Reagents
        # -------------------------
        # NOTE: Must satisfy your clean():
        # - rpv > upv
        # - if category.uses_cluster_dice: dice required
        reagent_seed = [
            {
                "name": "Aberrant Plant Seeds",
                "upv": 2,
                "rpv": 5,
                "refine_dc": 23,
                "search_dc": 18,
                "category": "Plant",
                "rarity": "Common",
                "cluster": (1, 10),
                "poisonous": False,
                "description": "An odd shrub whose leaves, trunk and color vary greatly, creating a mutated mish-mash of vegitation",
            },
            {
                "name": "Ace Cloves",
                "upv": 3,
                "rpv": 7,
                "refine_dc": 30,
                "search_dc": 21,
                "category": "Plant",
                "rarity": "Uncommon",
                "cluster": (1, 6),
                "poisonous": False,
                "description": "A 1 foot tall sprout with brown tabacco-like leaves. Bulbous spade-shaped protrusions stick out from the center.",
            },
            {
                "name": "Adder Venom",
                "upv": 1,
                "rpv": 2,
                "refine_dc": 14,
                "search_dc": 18,
                "category": "Other",
                "rarity": "Common",
                "cluster": (1, 4),
                "poisonous": True,
                "description": "A pale to milky-white snake about 2 feet in length with a pinkish underbelly.",
            },
            {
                "name": "Aegis Pebbles",
                "upv": 5,
                "rpv": 9,
                "refine_dc": 37,
                "search_dc": 14,
                "category": "Mineral",
                "rarity": "Rare",
                "cluster": (1, 5),
                "poisonous": False,
                "description": "Nearly spherical translucent blue stones which have a silver star-shaped metal bit in their center. Imagery reminiscent of the Astral Plane.",
            },
            {
                "name": "Ajax's Passion",
                "upv": 1,
                "rpv": 6,
                "refine_dc": 28,
                "search_dc": 14,
                "category": "Plant",
                "rarity": "Uncommon",
                "cluster": (1, 4),
                "poisonous": False,
                "description": "Large 5-petaled flower, 7~8 inches in diameter with a violet center. Black spots towards the edges.",
            },
            {
                "name": "Angel Feathers",
                "upv": 7,
                "rpv": 10,
                "refine_dc": 40,
                "category": "Carve",
                "rarity": "Rare",
                "poisonous": False,
                "description": "These are the long, pristine pinfeathers from the wings of a genuine celestial angel.",
            },
            {
                "name": "Angelhair Grass",
                "upv": 4,
                "rpv": 5,
                "refine_dc": 25,
                "search_dc": 18,
                "category": "Plant",
                "rarity": "Common",
                "cluster": (1, 8),
                "poisonous": False,
                "description": "Knee-high golden-yellow grass with very smooth edges. Feels soft to the touch and smells slightly lemony.",
            },
            {
                "name": "Apple Crow Feathers",
                "upv": 1,
                "rpv": 3,
                "refine_dc": 17,
                "search_dc": 18,
                "category": "Animal",
                "rarity": "Common",
                "cluster": (1, 4),
                "poisonous": False,
                "description": "A red-eyed bird, slightly smaller than a common crow. 4~5 inch long feathers which are black at the root and gradually turn dark red at the tip.",
            },
            {
                "name": "Aquatic Finch Eggs",
                "upv": 1,
                "rpv": 4,
                "refine_dc": 21,
                "search_dc": 27,
                "category": "Animal",
                "rarity": "Common",
                "cluster": (1, 4),
                "poisonous": False,
                "description": "Dark gray eggs with an uneven shape. Similar to river stones in appearance.",
            },
            {
                "name": "Archane Bladder",
                "upv": 2,
                "rpv": 4,
                "refine_dc": 22,
                "category": "Carve",
                "rarity": "Common",
                "poisonous": False,
                "description": "A bluish-purple fleshy sack within most magical creatures that produces an oily substance with properties similar to residuum.",
            },
            {
                "name": "Archane Salt",
                "upv": 4,
                "rpv": 7,
                "refine_dc": 29,
                "search_dc": 23,
                "category": "Mineral",
                "rarity": "Uncommon",
                "cluster": (1, 6),
                "poisonous": False,
                "description": "A mix of pink and light blue sand which begins to glow teal in the proximity of magic items or spells.",
            },
            {
                "name": "Archon Blood",
                "upv": 3,
                "rpv": 8,
                "refine_dc": 33,
                "category": "Carve",
                "rarity": "Uncommon",
                "poisonous": False,
                "description": "A highly unstable shimmering liquid found flowing through the bodies of archons. Can quickly and randomly change in density and viscosity.",
            },
            {
                "name": "Astrid's Plume",
                "upv": 2,
                "rpv": 3,
                "refine_dc": 19,
                "search_dc": 10,
                "category": "Plant",
                "rarity": "Common",
                "cluster": (1, 4),
                "poisonous": False,
                "description": "Long red-orange tubular flower with leathery petals and a feather-like stamen which sticks out twice the length of the flower.",
            },
            {
                "name": "Astral Calcium",
                "upv": 2,
                "rpv": 5,
                "refine_dc": 23,
                "category": "Carve",
                "rarity": "Common",
                "poisonous": False,
                "description": "A bluish-silver dust that can be scraped from the remains of a slain immortal being.",
            },
            {
                "name": "Azer Scalp",
                "upv": 4,
                "rpv": 5,
                "refine_dc": 24,
                "category": "Carve",
                "rarity": "Common",
                "poisonous": False,
                "description": "The red-orange hair of an Azer continues to glow and produce heat long after its death.",
            },
        ]

        reagents_by_name = {}
        for r in reagent_seed:
            cat = categories_by_name[r["category"]]
            rar = rarities_by_name[r["rarity"]]

            dice_count, dice_sides = r["cluster"]

            reagent, created = Reagent.objects.update_or_create(
                name=r["name"],
                defaults={
                    "upv": r["upv"],
                    "rpv": r["rpv"],
                    "description": r.get("description", ""),
                    "search_dc": r.get("search_dc"),
                    "refine_dc": r["refine_dc"],
                    "category": cat,
                    "rarity": rar,
                    "cluster_dice_count": dice_count,
                    "cluster_dice_sides": dice_sides,
                    "poisonous": r.get("poisonous", False),
                },
            )

            reagent.full_clean()
            reagent.save()

            reagents_by_name[reagent.name] = reagent
            self.stdout.write(f"{'➕' if created else '✔️'} Reagent: {reagent.name}")

        # -------------------------
        # 2) Biomes
        # -------------------------
        biome_seed = {
            "Desert": ["Ace Cloves"],
            "Forest": ["Aberrant Plant Seeds", "Adder Venom", "Ajax's Passion", "Angelhair Grass", "Apple Crow Feathers", "Astrid's Plume"],
            "Jungle": ["Aberrant Plant Seeds", "Adder Venom", "Aegis Pebbles", "Astrid's Plume"],
            "Freshwater": ["Adder Venom", "Angelhair Grass", "Aquatic Finch Eggs", "Archane Salt"],
            "Mountain": ["Angelhair Grass"],
            "Ocean": ["Aquatic Finch Eggs", "Archane Salt"],
            "Plains": ["Aberrant Plant Seeds", "Ace Cloves", "Adder Venom", "Apple Crow Feathers"],
            "Swamp": ["Aberrant Plant Seeds", "Adder Venom", "Aquatic Finch Eggs"],
            "Tundra": ["Angelhair Grass"],
            "Underground": ["Aegis Pebbles", "Archane Salt"],
            "Urban": [],
            "Volcanic": ["Aegis Pebbles", "Archane Salt", "Astrid's Plume"]
        }

        for biome_name, reagent_names in biome_seed.items():
            biome, created = Biome.objects.update_or_create(name=biome_name, defaults={})

            missing = [n for n in reagent_names if n not in reagents_by_name]
            if missing:
                raise ValueError(f"Biome '{biome_name}' references missing reagents: {missing}")

            biome.reagents.set([reagents_by_name[n] for n in reagent_names])

            self.stdout.write(f"{'➕' if created else '✔️'} Biome: {biome.name}")

        # -------------------------
        # 3) Potion Effects
        # -------------------------
        effects_seed = [
            {
                "name": "Healing",
                "lvls": {
                    1: "Spend a healing surge and gain 5 HP.",
                    2: "Spend a healing surge and gain 10 HP.",
                    3: "Spend a healing surge and gain 15 HP.",
                    4: "Spend a healing surge and gain that amount or 20 hp, whichever is higher.",
                    5: "Spend a healing surge and gain that amount or 25 hp, whichever is higher.",
                    6: "Spend a healing surge and gain that amount or 30 hp, whichever is higher.",
                    7: "Gain HP as if you had spent a healing surge.",
                    8: "Gain HP as if you had spent 2 healing surges.",
                    9: "Heal up to your max HP. No surge required.",
                    10: "Permanently increase your max HP by 5, then heal up to your new max HP.",
                },
                "reagents": ["Adder Venom", "Angel Feathers", "Angelhair Grass"],
            },
            {
                "name": "Defense Boost",
                "lvls": {
                    1: "Gain a +1 potion bonus to all defenses until the end of your next turn.",
                    2: "Gain a +1 potion bonus to all defenses until the end of the encounter.",
                    3: "Gain a +2 potion bonus to all defenses until the end of your next turn.",
                    4: "Gain a +2 potion bonus to all defenses until the end of the encounter.",
                    5: "Gain a +3 potion bonus to all defenses until the end of your next turn.",
                    6: "Gain a +3 potion bonus to all defenses until the end of the encounter.",
                    7: "Gain a +4 potion bonus to all defenses until the end of your next turn.",
                    8: "Gain a +4 potion bonus to all defenses until the end of the encounter.",
                    9: "Gain a +5 potion bonus to all defenses until the end of your next turn.",
                    10: "Gain a +5 potion bonus to all defenses until the end of the encounter, and gain a permanent +1 bonus to a defense of your choice.",
                },
                "reagents": [""],
            },
            {
                "name": "AC Boost",
                "lvls": {
                    1: "Gain a +2 potion bonus to AC until the end of your next turn.",
                    2: "Gain a +4 potion bonus to AC until the end of your next turn.",
                    3: "Gain a +6 potion bonus to AC until the end of your next turn.",
                    4: "Gain a +4 potion bonus to AC until the end of the encounter.",
                    5: "Gain a +6 potion bonus to AC until the end of the encounter.",
                    6: "Gain a +8 potion bonus to AC until the end of the encounter.",
                    7: "Gain a +6 potion bonus to AC for 1 hour.",
                    8: "Gain a +8 potion bonus to AC for 1 hour.",
                    9: "Gain a +10 potion bonus to AC for 1 hour.",
                    10: "Gain a +10 potion bonus to AC for 1 day, and a permanent +2 bonus to AC.",
                },
                "reagents": ["Angel Feathers", "Astral Calcium"],
            },
            {
                "name": "Will Boost",
                "lvls": {
                    1: "Gain a +2 potion bonus to Will until the end of your next turn.",
                    2: "Gain a +4 potion bonus to Will until the end of your next turn.",
                    3: "Gain a +6 potion bonus to Will until the end of your next turn.",
                    4: "Gain a +4 potion bonus to Will until the end of the encounter.",
                    5: "Gain a +6 potion bonus to Will until the end of the encounter.",
                    6: "Gain a +8 potion bonus to Will until the end of the encounter.",
                    7: "Gain a +6 potion bonus to Will for 1 hour.",
                    8: "Gain a +8 potion bonus to Will for 1 hour.",
                    9: "Gain a +10 potion bonus to Will for 1 hour.",
                    10: "Gain a +10 potion bonus to Will for 1 day, and a permanent +2 bonus to Will.",
                },
                "reagents": [""],
            },
            {
                "name": "Fortitude Boost",
                "lvls": {
                    1: "Gain a +2 potion bonus to Fortitude until the end of your next turn.",
                    2: "Gain a +4 potion bonus to Fortitude until the end of your next turn.",
                    3: "Gain a +6 potion bonus to Fortitude until the end of your next turn.",
                    4: "Gain a +4 potion bonus to Fortitude until the end of the encounter.",
                    5: "Gain a +6 potion bonus to Fortitude until the end of the encounter.",
                    6: "Gain a +8 potion bonus to Fortitude until the end of the encounter.",
                    7: "Gain a +6 potion bonus to Fortitude for 1 hour.",
                    8: "Gain a +8 potion bonus to Fortitude for 1 hour.",
                    9: "Gain a +10 potion bonus to Fortitude for 1 hour.",
                    10: "Gain a +10 potion bonus to Fortitude for 1 day, and a permanent +2 bonus to Fortitude.",
                },
                "reagents": ["Angel Feathers", "Apple Crow Feathers"],
            },
            {
                "name": "Reflex Boost",
                "lvls": {
                    1: "Gain a +2 potion bonus to Reflex until the end of your next turn.",
                    2: "Gain a +4 potion bonus to Reflex until the end of your next turn.",
                    3: "Gain a +6 potion bonus to Reflex until the end of your next turn.",
                    4: "Gain a +4 potion bonus to Reflex until the end of the encounter.",
                    5: "Gain a +6 potion bonus to Reflex until the end of the encounter.",
                    6: "Gain a +8 potion bonus to Reflex until the end of the encounter.",
                    7: "Gain a +6 potion bonus to Reflex for 1 hour.",
                    8: "Gain a +8 potion bonus to Reflex for 1 hour.",
                    9: "Gain a +10 potion bonus to Reflex for 1 hour.",
                    10: "Gain a +10 potion bonus to Reflex for 1 day, and a permanent +2 bonus to Reflex.",
                },
                "reagents": ["Angel Feathers", "Azer Scalp"],
            },
            {
                "name": "Attack Boost",
                "lvls": {
                    1: "+1 potion bonus to your attack rolls until the end of your next turn.",
                    2: "+1 potion bonus to your attack rolls until the end of the encounter.",
                    3: "+2 potion bonus to your attack rolls until the end of your next turn.",
                    4: "+2 potion bonus to your attack rolls until the end of the encounter.",
                    5: "+3 potion bonus to your attack rolls until the end of your next turn.",
                    6: "+3 potion bonus to your attack rolls until the end of the encounter.",
                    7: "+4 potion bonus to your attack rolls until the end of your next turn.",
                    8: "+4 potion bonus to your attack rolls until the end of the encounter.",
                    9: "+5 potion bonus to your attack rolls until the end of your next turn.",
                    10: "+5 potion bonus to your attack rolls until the end of the encounter, and gain a permanent +1 bonus to all attack rolls.",
                },
                "reagents": ["Astrid's Plume"],
            },
            {
                "name": "Martial Damage Boost",
                "lvls": {
                    1: "+2 potion bonus to your damage rolls using abilities with the Martial keyword until the end of your next turn.",
                    2: "+1 potion bonus to your damage rolls using abilities with the Martial keyword until the end of the encounter.",
                    3: "+4 potion bonus to your damage rolls using abilities with the Martial keyword until the end of your next turn.",
                    4: "+2 potion bonus to your damage rolls using abilities with the Martial keyword until the end of the encounter.",
                    5: "+6 potion bonus to your damage rolls using abilities with the Martial keyword until the end of your next turn.",
                    6: "+3 potion bonus to your damage rolls using abilities with the Martial keyword until the end of the encounter.",
                    7: "+8 potion bonus to your damage rolls using abilities with the Martial keyword until the end of your next turn.",
                    8: "+4 potion bonus to your damage rolls using abilities with the Martial keyword until the end of the encounter.",
                    9: "+5 potion bonus to your damage rolls using abilities with the Martial keyword until the end of your next turn.",
                    10: "+5 potion bonus to your damage rolls using abilities with the Martial keyword until the end of the encounter, and gain a permanent +1 bonus to damage rolls from Martial powers.",
                },
                "reagents": [""],
            },
            {
                "name": "Magic Damage Boost",
                "lvls": {
                    1: "+2 potion bonus to your damage rolls using Arcane, Divine, Primal or Psionic powers until the end of your next turn.",
                    2: "+1 potion bonus to your damage rolls using Arcane, Divine, Primal or Psionic powers until the end of the encounter.",
                    3: "+4 potion bonus to your damage rolls using Arcane, Divine, Primal or Psionic powers until the end of your next turn.",
                    4: "+2 potion bonus to your damage rolls using Arcane, Divine, Primal or Psionic powers until the end of the encounter.",
                    5: "+6 potion bonus to your damage rolls using Arcane, Divine, Primal or Psionic powers until the end of your next turn.",
                    6: "+3 potion bonus to your damage rolls using Arcane, Divine, Primal or Psionic powers until the end of the encounter.",
                    7: "+8 potion bonus to your damage rolls using Arcane, Divine, Primal or Psionic powers until the end of your next turn.",
                    8: "+4 potion bonus to your damage rolls using Arcane, Divine, Primal or Psionic powers until the end of the encounter.",
                    9: "+5 potion bonus to your damage rolls using Arcane, Divine, Primal or Psionic powers until the end of your next turn.",
                    10: "+5 potion bonus to your damage rolls using Arcane, Divine, Primal or Psionic powers until the end of the encounter, and gain a permanent +1 bonus to damage rolls from Martial powers.",
                },
                "reagents": ["Archane Bladder", "Archane Salt"],
            },
            {
                "name": "Fire Resistance",
                "lvls": {
                    1: "Gain Resist 2 to Fire until the end of the encounter.",
                    2: "Gain Resist 4 to Fire until the end of the encounter.",
                    3: "Gain Resist 6 to Fire until the end of the encounter.",
                    4: "Gain Resist 8 to Fire until the end of the encounter.",
                    5: "Gain Resist 10 to Fire until the end of the encounter.",
                    6: "Gain Resist 12 to Fire until the end of the encounter.",
                    7: "Gain Resist 14 to Fire until the end of the encounter.",
                    8: "Gain Resist 16 to Fire until the end of the encounter.",
                    9: "Gain Resist 18 to Fire until the end of the encounter.",
                    10: "Gain Resist 20 to Fire until the end of the encounter and a permanent Resist 5 to Fire (or +5 if you already have that resistance).",
                },
                "reagents": ["Azer Scalp"],
            },
            {
                "name": "Cold Resistance",
                "lvls": {
                    1: "Gain Resist 2 to Cold until the end of the encounter.",
                    2: "Gain Resist 4 to Cold until the end of the encounter.",
                    3: "Gain Resist 6 to Cold until the end of the encounter.",
                    4: "Gain Resist 8 to Cold until the end of the encounter.",
                    5: "Gain Resist 10 to Cold until the end of the encounter.",
                    6: "Gain Resist 12 to Cold until the end of the encounter.",
                    7: "Gain Resist 14 to Cold until the end of the encounter.",
                    8: "Gain Resist 16 to Cold until the end of the encounter.",
                    9: "Gain Resist 18 to Cold until the end of the encounter.",
                    10: "Gain Resist 20 to Cold until the end of the encounter and a permanent Resist 5 to Cold (or +5 if you already have that resistance).",
                },
                "reagents": ["Archon Blood"],
            },
            {
                "name": "Lightning Resistance",
                "lvls": {
                    1: "Gain Resist 2 to Lightning until the end of the encounter.",
                    2: "Gain Resist 4 to Lightning until the end of the encounter.",
                    3: "Gain Resist 6 to Lightning until the end of the encounter.",
                    4: "Gain Resist 8 to Lightning until the end of the encounter.",
                    5: "Gain Resist 10 to Lightning until the end of the encounter.",
                    6: "Gain Resist 12 to Lightning until the end of the encounter.",
                    7: "Gain Resist 14 to Lightning until the end of the encounter.",
                    8: "Gain Resist 16 to Lightning until the end of the encounter.",
                    9: "Gain Resist 18 to Lightning until the end of the encounter.",
                    10: "Gain Resist 20 to Lightning until the end of the encounter and a permanent Resist 5 to Lightning (or +5 if you already have that resistance).",
                },
                "reagents": ["Aberrant Plant Seeds", "Ajax's Passion", "Archane Salt", "Archon Blood"],
            },
            {
                "name": "Acid Resistance",
                "lvls": {
                    1: "Gain Resist 2 to Acid until the end of the encounter.",
                    2: "Gain Resist 4 to Acid until the end of the encounter.",
                    3: "Gain Resist 6 to Acid until the end of the encounter.",
                    4: "Gain Resist 8 to Acid until the end of the encounter.",
                    5: "Gain Resist 10 to Acid until the end of the encounter.",
                    6: "Gain Resist 12 to Acid until the end of the encounter.",
                    7: "Gain Resist 14 to Acid until the end of the encounter.",
                    8: "Gain Resist 16 to Acid until the end of the encounter.",
                    9: "Gain Resist 18 to Acid until the end of the encounter.",
                    10: "Gain Resist 20 to Acid until the end of the encounter and a permanent Resist 5 to Acid (or +5 if you already have that resistance).",
                },
                "reagents": [""],
            },
            {
                "name": "Poison Resistance",
                "lvls": {
                    1: "Gain Resist 2 to Poison until the end of the encounter.",
                    2: "Gain Resist 4 to Poison until the end of the encounter.",
                    3: "Gain Resist 6 to Poison until the end of the encounter.",
                    4: "Gain Resist 8 to Poison until the end of the encounter.",
                    5: "Gain Resist 10 to Poison until the end of the encounter.",
                    6: "Gain Resist 12 to Poison until the end of the encounter.",
                    7: "Gain Resist 14 to Poison until the end of the encounter.",
                    8: "Gain Resist 16 to Poison until the end of the encounter.",
                    9: "Gain Resist 18 to Poison until the end of the encounter.",
                    10: "Gain Resist 20 to Poison until the end of the encounter and a permanent Resist 5 to Poison (or +5 if you already have that resistance).",
                },
                "reagents": [""],
            },
            {
                "name": "Necrotic Resistance",
                "lvls": {
                    1: "Gain Resist 2 to Necrotic until the end of the encounter.",
                    2: "Gain Resist 4 to Necrotic until the end of the encounter.",
                    3: "Gain Resist 6 to Necrotic until the end of the encounter.",
                    4: "Gain Resist 8 to Necrotic until the end of the encounter.",
                    5: "Gain Resist 10 to Necrotic until the end of the encounter.",
                    6: "Gain Resist 12 to Necrotic until the end of the encounter.",
                    7: "Gain Resist 14 to Necrotic until the end of the encounter.",
                    8: "Gain Resist 16 to Necrotic until the end of the encounter.",
                    9: "Gain Resist 18 to Necrotic until the end of the encounter.",
                    10: "Gain Resist 20 to Necrotic until the end of the encounter and a permanent Resist 5 to Necrotic (or +5 if you already have that resistance).",
                },
                "reagents": ["Adder Venom"],
            },
            {
                "name": "Radiant Resistance",
                "lvls": {
                    1: "Gain Resist 2 to Radiant until the end of the encounter.",
                    2: "Gain Resist 4 to Radiant until the end of the encounter.",
                    3: "Gain Resist 6 to Radiant until the end of the encounter.",
                    4: "Gain Resist 8 to Radiant until the end of the encounter.",
                    5: "Gain Resist 10 to Radiant until the end of the encounter.",
                    6: "Gain Resist 12 to Radiant until the end of the encounter.",
                    7: "Gain Resist 14 to Radiant until the end of the encounter.",
                    8: "Gain Resist 16 to Radiant until the end of the encounter.",
                    9: "Gain Resist 18 to Radiant until the end of the encounter.",
                    10: "Gain Resist 20 to Radiant until the end of the encounter and a permanent Resist 5 to Radiant (or +5 if you already have that resistance).",
                },
                "reagents": ["Ace Cloves"],
            },
            {
                "name": "Psychic Resistance",
                "lvls": {
                    1: "Gain Resist 2 to Psychic until the end of the encounter.",
                    2: "Gain Resist 4 to Psychic until the end of the encounter.",
                    3: "Gain Resist 6 to Psychic until the end of the encounter.",
                    4: "Gain Resist 8 to Psychic until the end of the encounter.",
                    5: "Gain Resist 10 to Psychic until the end of the encounter.",
                    6: "Gain Resist 12 to Psychic until the end of the encounter.",
                    7: "Gain Resist 14 to Psychic until the end of the encounter.",
                    8: "Gain Resist 16 to Psychic until the end of the encounter.",
                    9: "Gain Resist 18 to Psychic until the end of the encounter.",
                    10: "Gain Resist 20 to Psychic until the end of the encounter and a permanent Resist 5 to Psychic (or +5 if you already have that resistance).",
                },
                "reagents": ["Aberrant Plant Seeds", "Aegis Pebbles", "Archon Blood"],
            },
            {
                "name": "Thunder Resistance",
                "lvls": {
                    1: "Gain Resist 2 to Thunder until the end of the encounter.",
                    2: "Gain Resist 4 to Thunder until the end of the encounter.",
                    3: "Gain Resist 6 to Thunder until the end of the encounter.",
                    4: "Gain Resist 8 to Thunder until the end of the encounter.",
                    5: "Gain Resist 10 to Thunder until the end of the encounter.",
                    6: "Gain Resist 12 to Thunder until the end of the encounter.",
                    7: "Gain Resist 14 to Thunder until the end of the encounter.",
                    8: "Gain Resist 16 to Thunder until the end of the encounter.",
                    9: "Gain Resist 18 to Thunder until the end of the encounter.",
                    10: "Gain Resist 20 to Thunder until the end of the encounter and a permanent Resist 5 to Thunder (or +5 if you already have that resistance).",
                },
                "reagents": [""],
            },
            {
                "name": "Weapon Resistance",
                "lvls": {
                    1: "Gain Resist 2 to Weapon and Untyped damage until the end of the encounter.",
                    2: "Gain Resist 4 to Weapon and Untyped damage until the end of the encounter.",
                    3: "Gain Resist 6 to Weapon and Untyped damage until the end of the encounter.",
                    4: "Gain Resist 8 to Weapon and Untyped damage until the end of the encounter.",
                    5: "Gain Resist 10 to Weapon and Untyped damage until the end of the encounter.",
                    6: "Gain Resist 12 to Weapon and Untyped damage until the end of the encounter.",
                    7: "Gain Resist 14 to Weapon and Untyped damage until the end of the encounter.",
                    8: "Gain Resist 16 to Weapon and Untyped damage until the end of the encounter.",
                    9: "Gain Resist 18 to Weapon and Untyped damage until the end of the encounter.",
                    10: "Gain Resist 20 to Weapon and Untyped damage until the end of the encounter and a permanent Resist 5 to Weapon and Untyped damage (or +5 if you already have it).",
                },
                "reagents": ["Astrid's Plume"],
            },
            {
                "name": "Damage Resistance",
                "lvls": {
                    1: "Gain damage reduction 1 until the end of the encounter.",
                    2: "Gain damage reduction 2 until the end of the encounter.",
                    3: "Gain damage reduction 3 until the end of the encounter.",
                    4: "Gain damage reduction 4 until the end of the encounter.",
                    5: "Gain damage reduction 5 until the end of the encounter.",
                    6: "Gain damage reduction 6 until the end of the encounter.",
                    7: "Gain damage reduction 7 until the end of the encounter.",
                    8: "Gain damage reduction 8 until the end of the encounter.",
                    9: "Gain damage reduction 9 until the end of the encounter.",
                    10: "Gain damage reduction 10 until the end of the encounter and a permanent damage reduction 2 (or +2 if you have it already).",
                },
                "reagents": [""],
            },
            {
                "name": "Temporary Health",
                "lvls": {
                    1: "Gain 5 temporary HP.",
                    2: "Gain 10 temporary HP.",
                    3: "Gain 15 temporary HP.",
                    4: "Gain 20 temporary HP.",
                    5: "Gain 25 temporary HP.",
                    6: "Gain 30 temporary HP.",
                    7: "Gain 35 temporary HP.",
                    8: "Gain 40 temporary HP.",
                    9: "Gain 45 temporary HP.",
                    10: "Gain 50 temporary HP. Gain a Daily Utility Power: Minor Action: Gain temporary HP equal to half your level + your Constitution modifier.",
                },
                "reagents": ["Ace Cloves", "Aegis Pebbles", "Angelhair Grass", "Archane Bladder"],
            },
            {
                "name": "Speed",
                "lvls": {
                    1: "Gain a +1 potion bonus to your speed until the end of your next turn.",
                    2: "Gain a +1 potion bonus to your speed until the end of the encounter.",
                    3: "Gain a +2 potion bonus to your speed until the end of your next turn.",
                    4: "Gain a +2 potion bonus to your speed until the end of the encounter.",
                    5: "Gain a +3 potion bonus to your speed until the end of your next turn.",
                    6: "Gain a +3 potion bonus to your speed until the end of the encounter.",
                    7: "Gain a +4 potion bonus to your speed until the end of your next turn.",
                    8: "Gain a +5 potion bonus to your speed until the end of the encounter.",
                    9: "Gain a +6 potion bonus to your speed until the end of the encounter.",
                    10: "Gain a +8 potion bonus to your speed until the end of the encounter, and a permanent +1 bonus to your speed.",
                },
                "reagents": [""],
            },
            {
                "name": "Regeneration",
                "lvls": {
                    1: "Gain regeneration 1 until the end of the encounter.",
                    2: "Gain regeneration 2 until the end of the encounter.",
                    3: "Gain regeneration 3 until the end of the encounter.",
                    4: "Gain regeneration 5 until the end of the encounter.",
                    5: "Gain regeneration 8 until the end of the encounter.",
                    6: "Gain regeneration 10 until the end of the encounter.",
                    7: "Gain regeneration 12 until the end of the encounter.",
                    8: "Gain regeneration 15 until the end of the encounter.",
                    9: "Gain regeneration 20 until the end of the encounter.",
                    10: "Gain regeneration 25 until the end of the encounter. Gain a Daily Utility Power: Minor Action: Until the end of the encounter, you have regeneration 5 while you are bloodied.",
                },
                "reagents": [""],
            },
            {
                "name": "Flight",
                "lvls": {
                    1: "Gain a flight speed of 4 until the end of your next turn.",
                    2: "Gain a flight speed of 5 until the end of your next turn.",
                    3: "Gain a flight speed of 6 until the end of your next turn.",
                    4: "Gain a flight speed of 8 until the end of your next turn.",
                    5: "Gain a flight speed of 10 until the end of your next turn.",
                    6: "Gain a flight speed of 6 until the end of the encounter.",
                    7: "Gain a flight speed of 8 until the end of the encounter.",
                    8: "Gain a flight speed of 10 until the end of the encounter.",
                    9: "Gain a flight speed of 8 for one hour.",
                    10: "Gain a flight speed of 8 until you take a long rest. Gain a Daily Utility power: Minor Action: Gain a flight speed of 10 until the end of your next turn.",
                },
                "reagents": ["Apple Crow Feathers", "Astral Calcium"],
            },
            {
                "name": "Water Walking",
                "lvls": {
                    1: "Gain the ability to move on water at half your speed as if it were normal terrain until the end of your next turn.",
                    2: "Gain the ability to move on water at your speed as if it were normal terrain until the end of your next turn.",
                    3: "Gain the ability to move on water at your speed as if it were normal terrain until the end of the encounter.",
                    4: "Gain the ability to move on water or ice at your speed as if it were normal terrain until the end of the encounter.",
                    5: "Gain the ability to move on water or ice at your speed as if it were normal terrain for one hour.",
                    6: "Gain the ability to move on water or ice at your speed for one hour. You may also move across harmful liquids such as acid or lava, but if you end your movement there, you fall in. You are subject to damage as you cross dangerous liquids.",
                    7: "Gain the ability to move on any liquid or ice at your speed for one hour. You are subject to damage as you cross dangerous liquids.",
                    8: "Gain the ability to move on any liquid or ice at your speed for one hour. You take no damage from liquid or ice surfaces as long as you are standing.",
                    9: "Gain the ability to move on any liquid or ice at your speed for one day. You take no damage from liquid or ice surfaces as long as you are not prone or submerged.",
                    10: "Gain the ability to move on any liquid or ice at your speed for one day. You take no damage from liquid or ice surfaces as long as you are not submerged. You may elect to turn liquid squares into their solid form as you walk across them. If you do, they remain solid until the end of the encounter. You also permanently gain the ability to walk on water at your speed.",
                },
                "reagents": ["Ajax's Passion"],
            },
            {
                "name": "Water Breathing",
                "lvls": {
                    1: "Gain Water Breathing until the end of your next turn.",
                    2: "Gain Water Breathing for 1 minute.",
                    3: "Gain Water Breathing for 5 minutes.",
                    4: "Gain Water Breathing for 10 minutes.",
                    5: "Gain Water Breathing for 30 minutes.",
                    6: "Gain Water Breathing for 1 hour.",
                    7: "Gain Water Breathing for 3 hours.",
                    8: "Gain Water Breathing for 12 hours.",
                    9: "Gain Water Breathing for 1 day.",
                    10: "Permanently gain the ability to breathe underwater. This ability does not apply to other liquids.",
                },
                "reagents": ["Aegis Pebbles", "Aquatic Finch Eggs"],
            },
            {
                "name": "Invisibility",
                "lvls": {
                    1: "You become invisible until the end of your next turn. You still must make Stealth checks.",
                    2: "You become invisible until the end of the encounter or until you take any action other than standing still and hiding.",
                    3: "You become invisible until the end of the encounter or until you attack or move more than 1 square on your turn.",
                    4: "You become invisible until the end of the encounter or until you attack or move more than 2 squares on your turn.",
                    5: "You become invisible until the end of the encounter or until you attack or move more than half your speed on your turn.",
                    6: "You become invisible until the end of the encounter or until you attack.",
                    7: "You become invisible until the end of the encounter or until you make a melee attack.",
                    8: "You become invisible until the end of the encounter.",
                    9: "You become invisible for 1 hour.",
                    10: "You become invisible for 1 day, and gain a permanent Daily Utility: Minor Action: You become invisible until you attack or move more than half your speed on your turn.",
                },
                "reagents": [""],
            },
            {
                "name": "Slow Fall",
                "lvls": {
                    1: "Until the end of your next turn, you fall at a rate of 3 squares (15 ft.) per round.",
                    2: "Until the end of your next turn, you fall at a rate of 6 squares (30 ft.) per round.",
                    3: "Until the end of your next turn, you fall at a rate of 10 squares (50 ft.) per round.",
                    4: "Until the end of the encounter, you fall at a rate of 3 squares (15 ft.) per round.",
                    5: "Until the end of the encounter, you fall at a rate of 6 squares (30 ft.) per round.",
                    6: "Until the end of the encounter, you fall at a rate of 10 squares (50 ft.) per round.",
                    7: "Until the end of the encounter, you can control the rate of your decent, anywhere from 3 to 10 squares (15 to 50 ft.) per round.",
                    8: "For 1 hour, you can control the rate of your decent, anywhere from 1 to 30 squares (5 to 150 ft.) per round.",
                    9: "For 1 hour, you can control the rate of your decent, anywhere from 0 to 115 squares (0 to 575 ft.) per round.",
                    10: "For 1 day, you can control the rate of your decent, anywhere from 0 to 115 squares (0 to 575 ft.) per round. Gain a permanent Daily Utility: Free Action: Until the end of the encounter, you fall at a rate of 6 squares (30 ft.) per round.",
                },
                "reagents": [""],
            },
            {
                "name": "Spider Climb",
                "lvls": {
                    1: "Until the end of your next turn, you automatically succeed at Athletics checks to climb vertical surfaces. (Half speed, as normal.)",
                    2: "Until the end of your next turn, you automatically succeed at Athletics checks to climb vertical surfaces. You can climb at your speed.",
                    3: "Until the end of the encounter, you automatically succeed at Athletics checks to climb vertical surfaces. (Half speed, as normal.)",
                    4: "Until the end of the encounter, you automatically succeed at Athletics checks to climb vertical surfaces. You can climb at your speed.",
                    5: "Until the end of the encounter, you gain a climb speed equal to your speed and can move on ceilings at half your speed.",
                    6: "Until the end of the encounter, you gain a climb speed equal to your speed and can move on ceilings.",
                    7: "For one hour, you gain a climb speed equal to your speed and can move on ceilings.",
                    8: "For one hour, you gain a climb speed equal to your speed and can move on ceilings. If you wish, you may leave a trail of sticky spider web behind in squares you move through, turning them into difficult terrain for anyone but you.  It takes a standard action to clear away one square of webbing.",
                    9: "For one hour, you gain a climb speed equal to your speed and can move on ceilings. If you wish, you may leave a trail of sticky spider web behind in squares you move through, turning them into difficult terrain for anyone but you.  It takes a standard action to clear away one square of webbing. You may lower yourself from ceilings or overhangs by a thread of web at your speed, and can likewise climb back up. These threads disolve after 5 minutes.",
                    10: "For one day, you gain a climb speed equal to your speed and can move on ceilings. If you wish, you may leave a trail of sticky spider web behind in squares you move through, turning them into difficult terrain for anyone but you.  It takes a standard action to clear away one square of webbing. You may lower yourself from ceilings or overhangs by a thread of web at your speed, and can likewise climb back up. These threads disolve after 5 minutes. Gain a permanent Daily Utility power: Minor Action: Until the end of the encounter, you gain a climb speed equal to your speed and can move on ceilings at half your speed.",
                },
                "reagents": ["Adder Venom"],
            },
            {
                "name": "Darkvision",
                "lvls": {
                    1: "Gain Darkvision up to 6 squares (30 ft.) for 1 minute.",
                    2: "Gain Darkvision up to 10 squares (50 ft.) for 1 minute.",
                    3: "Gain Darkvision up to 12 squares (60 ft.) for 5 minutes.",
                    4: "Gain Darkvision up to 16 squares (80 ft.) for 5 minutes.",
                    5: "Gain Darkvision up to 20 squares (100 ft.) for 5 minutes.",
                    6: "Gain Darkvision up to 50 squares (250 ft.) for 5 minutes.",
                    7: "Gain Darkvision up to 50 squares (250 ft.) for 1 hour.",
                    8: "Gain Darkvision with unlimited distance for 1 hour.",
                    9: "Gain Darkvision with unlimited distance for 6 hours. This effect works even in magical darkness.",
                    10: "Gain Darkvision with unlimited distance for 1 day. This effect works even in magical darkness. Permanently gain Darkvision up to 20 squares (100 ft.)",
                },
                "reagents": ["Aegis Pebbles", "Archane Salt"],
            },
            {
                "name": "Cure Poison",
                "lvls": {
                    1: "Make a saving throw against one source of ongoing Poison damage.",
                    2: "Make a saving throw against any single effect that has the Poison keyword.",
                    3: "Make a saving throw against any single effect that has the Poison keyword with a +2 potion bonus.",
                    4: "Make a saving throw against any single effect that has the Poison keyword with a +5 potion bonus.",
                    5: "Make a saving throw against each effect that has the Poison keyword, each with a +5 potion bonus.",
                    6: "Instantly save against a single effect that has the Poison keyword.",
                    7: "Instantly save against a single effect that has the Poison keyword. You are immune to ongoing and status condition effects resulting from that type of poison for the rest of the encounter.",
                    8: "Instantly save against all effects that have the Poison keyword. You are immune to all of the ongoing and status condition effects resulting from the poisons you saved from for the rest of the encounter.",
                    9: "Instantly save against all effects that have the Poison keyword. You are immune to ongoing and status condition effects that would result from any attack that has the Poison keyword until the end of the encounter.",
                    10: "Instantly save against all effects that have the Poison keyword. You are immune to ongoing and status condition effects that would result from any attack that has the Poison keyword for 1 hour. Gain a permanent Daily Utility power: Minor Action: Instantly save against a single effect that has the Poison keyword.",
                },
                "reagents": ["Aberrant Plant Seeds"],
            },
            {
                "name": "Neutralize",
                "lvls": {
                    1: "Make a saving throw against one type of ongoing damage. Choose from Fire, Cold, Lightning, Thunder, Acid, Necrotic or Radiant.",
                    2: "",
                    3: "",
                    4: "",
                    5: "",
                    6: "",
                    7: "",
                    8: "",
                    9: "",
                    10: "",
                },
                "reagents": ["Archon Blood"],
            },
            {
                "name": "Polymorph",
                "lvls": {
                    1: "",
                    2: "",
                    3: "",
                    4: "",
                    5: "",
                    6: "",
                    7: "",
                    8: "",
                    9: "",
                    10: "",
                },
                "reagents": [""],
            },
            {
                "name": "Truesight",
                "lvls": {
                    1: "",
                    2: "",
                    3: "",
                    4: "",
                    5: "",
                    6: "",
                    7: "",
                    8: "",
                    9: "",
                    10: "",
                },
                "reagents": ["Astrid's Plume"],
            },
            {
                "name": "Phasing",
                "lvls": {
                    1: "",
                    2: "",
                    3: "",
                    4: "",
                    5: "",
                    6: "",
                    7: "",
                    8: "",
                    9: "",
                    10: "",
                },
                "reagents": [""],
            },
            {
                "name": "Alertness",
                "lvls": {
                    1: "",
                    2: "",
                    3: "",
                    4: "",
                    5: "",
                    6: "",
                    7: "",
                    8: "",
                    9: "",
                    10: "",
                },
                "reagents": ["Astrid's Plume"],
            },
            {
                "name": "Acrobatics Boost",
                "lvls": {
                    1: "",
                    2: "",
                    3: "",
                    4: "",
                    5: "",
                    6: "",
                    7: "",
                    8: "",
                    9: "",
                    10: "",
                },
                "reagents": ["Angelhair Grass"],
            },
            {
                "name": "Athletics Boost",
                "lvls": {
                    1: "",
                    2: "",
                    3: "",
                    4: "",
                    5: "",
                    6: "",
                    7: "",
                    8: "",
                    9: "",
                    10: "",
                },
                "reagents": ["Azer Scalp"],
            },
            {
                "name": "Endurance Boost",
                "lvls": {
                    1: "",
                    2: "",
                    3: "",
                    4: "",
                    5: "",
                    6: "",
                    7: "",
                    8: "",
                    9: "",
                    10: "",
                },
                "reagents": ["Astral Calcium"],
            },
            {
                "name": "Perception Boost",
                "lvls": {
                    1: "",
                    2: "",
                    3: "",
                    4: "",
                    5: "",
                    6: "",
                    7: "",
                    8: "",
                    9: "",
                    10: "",
                },
                "reagents": [""],
            },
            {
                "name": "Blinding",
                "lvls": {
                    1: "",
                    2: "",
                    3: "",
                    4: "",
                    5: "",
                    6: "",
                    7: "",
                    8: "",
                    9: "",
                    10: "",
                },
                "reagents": [""],
            },
            {
                "name": "Confusion",
                "lvls": {
                    1: "",
                    2: "",
                    3: "",
                    4: "",
                    5: "",
                    6: "",
                    7: "",
                    8: "",
                    9: "",
                    10: "",
                },
                "reagents": ["Apple Crow Feathers", "Archane Salt"],
            },
            {
                "name": "Fear",
                "lvls": {
                    1: "",
                    2: "",
                    3: "",
                    4: "",
                    5: "",
                    6: "",
                    7: "",
                    8: "",
                    9: "",
                    10: "",
                },
                "reagents": [""],
            },
            {
                "name": "Sleep",
                "lvls": {
                    1: "",
                    2: "",
                    3: "",
                    4: "",
                    5: "",
                    6: "",
                    7: "",
                    8: "",
                    9: "",
                    10: "",
                },
                "reagents": ["Aquatic Finch Eggs"],
            },
            {
                "name": "Slowness",
                "lvls": {
                    1: "",
                    2: "",
                    3: "",
                    4: "",
                    5: "",
                    6: "",
                    7: "",
                    8: "",
                    9: "",
                    10: "",
                },
                "reagents": [""],
            },
            {
                "name": "Daze",
                "lvls": {
                    1: "",
                    2: "",
                    3: "",
                    4: "",
                    5: "",
                    6: "",
                    7: "",
                    8: "",
                    9: "",
                    10: "",
                },
                "reagents": [""],
            },
            {
                "name": "Stun",
                "lvls": {
                    1: "",
                    2: "",
                    3: "",
                    4: "",
                    5: "",
                    6: "",
                    7: "",
                    8: "",
                    9: "",
                    10: "",
                },
                "reagents": ["Apple Crow Feathers"],
            },
            {
                "name": "Weakness",
                "lvls": {
                    1: "",
                    2: "",
                    3: "",
                    4: "",
                    5: "",
                    6: "",
                    7: "",
                    8: "",
                    9: "",
                    10: "",
                },
                "reagents": [""],
            },
            {
                "name": "Immobilize",
                "lvls": {
                    1: "",
                    2: "",
                    3: "",
                    4: "",
                    5: "",
                    6: "",
                    7: "",
                    8: "",
                    9: "",
                    10: "",
                },
                "reagents": [""],
            },
            {
                "name": "Petrification",
                "lvls": {
                    1: "",
                    2: "",
                    3: "",
                    4: "",
                    5: "",
                    6: "",
                    7: "",
                    8: "",
                    9: "",
                    10: "",
                },
                "reagents": [""],
            },
            {
                "name": "Fire Vulnerability",
                "lvls": {
                    1: "",
                    2: "",
                    3: "",
                    4: "",
                    5: "",
                    6: "",
                    7: "",
                    8: "",
                    9: "",
                    10: "",
                },
                "reagents": [""],
            },
            {
                "name": "Cold Vulnerability",
                "lvls": {
                    1: "",
                    2: "",
                    3: "",
                    4: "",
                    5: "",
                    6: "",
                    7: "",
                    8: "",
                    9: "",
                    10: "",
                },
                "reagents": ["Aquatic Finch Eggs", "Azer Scalp"],
            },
            {
                "name": "Lightning Vulnerability",
                "lvls": {
                    1: "",
                    2: "",
                    3: "",
                    4: "",
                    5: "",
                    6: "",
                    7: "",
                    8: "",
                    9: "",
                    10: "",
                },
                "reagents": ["Ace Cloves"],
            },
            {
                "name": "Thunder Vulnerability",
                "lvls": {
                    1: "",
                    2: "",
                    3: "",
                    4: "",
                    5: "",
                    6: "",
                    7: "",
                    8: "",
                    9: "",
                    10: "",
                },
                "reagents": [""],
            },
            {
                "name": "Necrotic Vulnerability",
                "lvls": {
                    1: "",
                    2: "",
                    3: "",
                    4: "",
                    5: "",
                    6: "",
                    7: "",
                    8: "",
                    9: "",
                    10: "",
                },
                "reagents": ["Astral Calcium"],
            },
            {
                "name": "Radiant Vulnerability",
                "lvls": {
                    1: "",
                    2: "",
                    3: "",
                    4: "",
                    5: "",
                    6: "",
                    7: "",
                    8: "",
                    9: "",
                    10: "",
                },
                "reagents": [""],
            },
            {
                "name": "Acid Vulnerability",
                "lvls": {
                    1: "",
                    2: "",
                    3: "",
                    4: "",
                    5: "",
                    6: "",
                    7: "",
                    8: "",
                    9: "",
                    10: "",
                },
                "reagents": [""],
            },
            {
                "name": "Poison Vulnerability",
                "lvls": {
                    1: "",
                    2: "",
                    3: "",
                    4: "",
                    5: "",
                    6: "",
                    7: "",
                    8: "",
                    9: "",
                    10: "",
                },
                "reagents": ["Ajax's Passion", "Angelhair Grass", "Archane Bladder"],
            },
            {
                "name": "Psychic Vulnerability",
                "lvls": {
                    1: "",
                    2: "",
                    3: "",
                    4: "",
                    5: "",
                    6: "",
                    7: "",
                    8: "",
                    9: "",
                    10: "",
                },
                "reagents": [""],
            },
            {
                "name": "Weapon Vulnerability",
                "lvls": {
                    1: "",
                    2: "",
                    3: "",
                    4: "",
                    5: "",
                    6: "",
                    7: "",
                    8: "",
                    9: "",
                    10: "",
                },
                "reagents": ["Aberrant Plant Seeds"],
            },
            {
                "name": "Poisoning",
                "lvls": {
                    1: "",
                    2: "",
                    3: "",
                    4: "",
                    5: "",
                    6: "",
                    7: "",
                    8: "",
                    9: "",
                    10: "",
                },
                "reagents": ["Adder Venom"],
            },
            {
                "name": "Attack Down",
                "lvls": {
                    1: "",
                    2: "",
                    3: "",
                    4: "",
                    5: "",
                    6: "",
                    7: "",
                    8: "",
                    9: "",
                    10: "",
                },
                "reagents": [""],
            },
            {
                "name": "Will Impairment",
                "lvls": {
                    1: "",
                    2: "",
                    3: "",
                    4: "",
                    5: "",
                    6: "",
                    7: "",
                    8: "",
                    9: "",
                    10: "",
                },
                "reagents": ["Ajax's Passion", "Aquatic Finch Eggs"],
            },
            {
                "name": "Fortitude Impairment",
                "lvls": {
                    1: "",
                    2: "",
                    3: "",
                    4: "",
                    5: "",
                    6: "",
                    7: "",
                    8: "",
                    9: "",
                    10: "",
                },
                "reagents": ["Archane Bladder"],
            },
            {
                "name": "Reflex Impairment",
                "lvls": {
                    1: "",
                    2: "",
                    3: "",
                    4: "",
                    5: "",
                    6: "",
                    7: "",
                    8: "",
                    9: "",
                    10: "",
                },
                "reagents": [""],
            },
            {
                "name": "Good Luck",
                "lvls": {
                    1: "",
                    2: "",
                    3: "",
                    4: "",
                    5: "",
                    6: "",
                    7: "",
                    8: "",
                    9: "",
                    10: "",
                },
                "reagents": ["Ace Cloves"],
            },
        ]

        for e in effects_seed:
            lvls = e["lvls"]
            effect, created = PotionEffect.objects.update_or_create(
                name=e["name"],
                defaults={f"lvl{i}": lvls[i] for i in range(1, 11)},
            )

            missing = [n for n in e["reagents"] if n not in reagents_by_name]
            if missing:
                raise ValueError(f"PotionEffect '{e['name']}' references missing reagents: {missing}")

            effect.reagents.set([reagents_by_name[n] for n in e["reagents"]])

            self.stdout.write(f"{'➕' if created else '✔️'} PotionEffect: {effect.name}")

        self.stdout.write(self.style.SUCCESS("✅ Seeding complete."))