# Generated by Django 5.2.7 on 2026-03-17 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        ('reagents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeUnlockEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_learned', models.CharField(choices=[('unrefined_test', 'Unrefined Test'), ('refined_test', 'Refined Test'), ('used_potion', 'Used Potion'), ('education', 'Education'), ('field_discovery', 'Field Discovery'), ('from_gm', 'From GM')], max_length=20)),
                ('what_learned', models.CharField(choices=[('learned_name', 'Learned Name'), ('learned_description', 'Learned Description'), ('learned_upv', 'Learned UPV'), ('learned_rpv', 'Learned RPV'), ('learned_category', 'Learned Category'), ('learned_rarity', 'Learned Rarity'), ('learned_biome', 'Learned Biome'), ('learned_effect', 'Learned Effect')], max_length=25)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('biome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_events', to='reagents.biome')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_events', to='characters.character')),
                ('effect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_events', to='reagents.potioneffect')),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_events', to='reagents.reagent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CharacterReagentBiome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('biome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='known_for_reagents', to='reagents.biome')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reagent_biome_knowledge', to='characters.character')),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='known_biomes_by_characters', to='reagents.reagent')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('character', 'reagent', 'biome'), name='unique_character_reagent_biome')],
            },
        ),
        migrations.CreateModel(
            name='CharacterReagentEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reagent_effect_knowledge', to='characters.character')),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='known_for_reagents', to='reagents.potioneffect')),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='known_effects_by_characters', to='reagents.reagent')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('character', 'reagent', 'effect'), name='unique_character_reagent_effect')],
            },
        ),
        migrations.CreateModel(
            name='CharacterReagentKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knows_name', models.BooleanField(default=False)),
                ('knows_description', models.BooleanField(default=False)),
                ('knows_upv', models.BooleanField(default=False)),
                ('knows_rpv', models.BooleanField(default=False)),
                ('knows_category', models.BooleanField(default=False)),
                ('knows_rarity', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reagent_knowledge', to='characters.character')),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='character_knowledge', to='reagents.reagent')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('character', 'reagent'), name='unique_character_reagent_knowledge')],
            },
        ),
        migrations.CreateModel(
            name='CharacterReagentMix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mix_result', models.CharField(choices=[('success', 'Success'), ('dud', 'Dud')], max_length=10)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reagent_mixes', to='characters.character')),
                ('discovered_effect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discovered_via_mix', to='reagents.potioneffect')),
                ('reagent_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mixes_as_first', to='reagents.reagent')),
                ('reagent_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mixes_as_second', to='reagents.reagent')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('character', 'reagent_a', 'reagent_b'), name='unique_character_mix')],
            },
        ),
    ]
