# Generated by Django 5.2.7 on 2026-04-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_characterreagentmix_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterreagentknowledge',
            name='notes',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
