# Generated by Django 5.2.7 on 2025-12-26 08:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('uses_cluster_dice', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MonsterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('tiny', 'Tiny (or minion)'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('huge', 'Huge'), ('gargantuan', 'Gargantuan'), ('colossal', 'Colossal')], max_length=20)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='reagent.monster')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddField(
            model_name='monster',
            name='types',
            field=models.ManyToManyField(related_name='monsters', to='reagent.monstertype'),
        ),
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('upv', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('rpv', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)])),
                ('description', models.TextField(blank=True, null=True)),
                ('search_dc', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('refine_dc', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('cluster_dice_count', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('cluster_dice_sides', models.PositiveSmallIntegerField(blank=True, choices=[(4, 'd4'), (6, 'd6'), (8, 'd8'), (10, 'd10'), (12, 'd12'), (20, 'd20')], null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='reagents/')),
                ('poisonous', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reagents', to='reagent.category')),
                ('rarity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reagents', to='reagent.rarity')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PotionEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('lvl1', models.CharField(max_length=500)),
                ('lvl2', models.CharField(max_length=500)),
                ('lvl3', models.CharField(max_length=500)),
                ('lvl4', models.CharField(max_length=500)),
                ('lvl5', models.CharField(max_length=500)),
                ('lvl6', models.CharField(max_length=500)),
                ('lvl7', models.CharField(max_length=500)),
                ('lvl8', models.CharField(max_length=500)),
                ('lvl9', models.CharField(max_length=500)),
                ('lvl10', models.CharField(max_length=500)),
                ('reagents', models.ManyToManyField(related_name='potion_effects', to='reagent.reagent')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Biome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('reagents', models.ManyToManyField(related_name='biomes', to='reagent.reagent')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EncounterReagentAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='reagent.encounter')),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounter_awards', to='reagent.reagent')),
            ],
            options={
                'ordering': ['encounter_id', 'reagent__name'],
                'constraints': [models.UniqueConstraint(fields=('encounter', 'reagent'), name='uniq_award_encounter_reagent')],
            },
        ),
    ]
