# Generated by Django 5.2.7 on 2026-03-19 08:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('uses_cluster_dice', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('upv', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('rpv', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)])),
                ('description', models.TextField(blank=True, null=True)),
                ('search_dc', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('refine_dc', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('cluster_dice_count', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('cluster_dice_sides', models.PositiveSmallIntegerField(blank=True, choices=[(4, 'd4'), (6, 'd6'), (8, 'd8'), (10, 'd10'), (12, 'd12'), (20, 'd20')], null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='reagents/')),
                ('poisonous', models.BooleanField(default=False)),
                ('vibration', models.BooleanField(default=False)),
                ('light_source', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reagents', to='reagents.category')),
                ('rarity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reagents', to='reagents.rarity')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PotionEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reagents', models.ManyToManyField(related_name='potion_effects', to='reagents.reagent')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Biome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('desert', 'Desert'), ('forest', 'Forest'), ('freshwater', 'Freshwater'), ('jungle', 'Jungle'), ('mountain', 'Mountain'), ('ocean', 'Ocean'), ('plains', 'Plains'), ('swamp', 'Swamp'), ('tundra', 'Tundra'), ('underground', 'Underground'), ('urban', 'Urban'), ('volcanic', 'Volcanic')], max_length=15, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reagents', models.ManyToManyField(related_name='biomes', to='reagents.reagent')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PotionEffectLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('rules_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('potion_effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effect_levels', to='reagents.potioneffect')),
            ],
            options={
                'ordering': ['potion_effect', 'level'],
                'constraints': [models.UniqueConstraint(fields=('potion_effect', 'level'), name='unique_level_per_effect')],
            },
        ),
        migrations.AddConstraint(
            model_name='reagent',
            constraint=models.CheckConstraint(condition=models.Q(('rpv__gt', models.F('upv'))), name='reagent_rpv_greater_than_upv'),
        ),
        migrations.AddConstraint(
            model_name='reagent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cluster_dice_count__isnull', True), ('cluster_dice_sides__isnull', True)), models.Q(('cluster_dice_count__isnull', False), ('cluster_dice_sides__isnull', False)), _connector='OR'), name='reagent_cluster_dice_both_or_neither'),
        ),
    ]
