# Generated by Django 5.2.7 on 2026-03-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biome',
            name='name',
            field=models.CharField(choices=[('Desert', 'Desert'), ('Forest', 'Forest'), ('Freshwater', 'Freshwater'), ('Jungle', 'Jungle'), ('Mountain', 'Mountain'), ('Ocean', 'Ocean'), ('Plains', 'Plains'), ('Swamp', 'Swamp'), ('Tundra', 'Tundra'), ('Underground', 'Underground'), ('Urban', 'Urban'), ('Volcanic', 'Volcanic')], max_length=15, unique=True),
        ),
    ]
