# Generated by Django 5.2.7 on 2026-03-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0002_alter_biome_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biome',
            name='name',
            field=models.CharField(choices=[('desert', 'Desert'), ('forest', 'Forest'), ('freshwater', 'Freshwater'), ('jungle', 'Jungle'), ('mountain', 'Mountain'), ('ocean', 'Ocean'), ('plains', 'Plains'), ('swamp', 'Swamp'), ('tundra', 'Tundra'), ('underground', 'Underground'), ('urban', 'Urban'), ('volcanic', 'Volcanic')], max_length=15, unique=True),
        ),
    ]
