# Generated by Django 5.2.7 on 2026-03-31 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equippeditem',
            name='inventory_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipped_as', to='inventory.inventoryitem'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.UniqueConstraint(condition=models.Q(('campaign__isnull', False)), fields=('name', 'campaign'), name='unique_character_name_per_campaign'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.UniqueConstraint(condition=models.Q(('campaign__isnull', False)), fields=('campaign', 'slug'), name='unique_slug_per_campaign'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.UniqueConstraint(condition=models.Q(('campaign__isnull', True)), fields=('owner', 'slug'), name='unique_slug_no_campaign'),
        ),
        migrations.AddConstraint(
            model_name='equippeditem',
            constraint=models.UniqueConstraint(fields=('character', 'slot'), name='unique_item_per_slot'),
        ),
    ]
