# Generated by Django 5.2.7 on 2026-03-17 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquippedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('head', 'Head'), ('neck', 'Neck'), ('armor', 'Armor'), ('arm', 'Arm'), ('hand', 'Hand'), ('weapon_1', 'Weapon (Main Hand)'), ('weapon_2', 'Weapon (Off Hand)'), ('implement_1', 'Implement (Main)'), ('implement_2', 'Implement (Secondary)'), ('waist', 'Waist'), ('feet', 'Feet'), ('ring_1', 'Ring (1)'), ('ring_2', 'Ring (2)')], max_length=15)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipped_items', to='characters.character')),
                ('inventory_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipped_as', to='inventory.inventoryitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('character', 'slot'), name='unique_item_per_slot')],
            },
        ),
    ]
