# Generated by Django 5.2.7 on 2026-04-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='lab_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='lab_time_unlimited',
            field=models.BooleanField(default=False),
        ),
    ]
