# Generated by Django 5.2.7 on 2026-03-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_equippeditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equippeditem',
            name='slot',
            field=models.CharField(choices=[('head', 'Head'), ('neck', 'Neck'), ('armor', 'Armor'), ('arm', 'Arm'), ('hand', 'Hand'), ('hand_1', 'Main Hand'), ('hand_2', 'Off Hand'), ('waist', 'Waist'), ('feet', 'Feet'), ('ring_1', 'Ring (1)'), ('ring_2', 'Ring (2)')], max_length=15),
        ),
    ]
