# Generated by Django 5.2.7 on 2026-03-27 05:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_unique_campaign_name_per_owner'),
        ('characters', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='character',
            name='unique_slug_no_campaign',
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.UniqueConstraint(condition=models.Q(('campaign__isnull', True)), fields=('owner', 'slug'), name='unique_slug_no_campaign'),
        ),
    ]
