# Generated by Django 5.2.7 on 2026-03-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_add_character_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
