# Generated by Django 5.2.7 on 2026-03-27 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_unique_campaign_name_per_owner'),
        ('characters', '0005_add_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='home_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_characters', to='campaigns.campaign'),
        ),
    ]
