# Generated by Django 5.2.7 on 2026-03-17 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_type', models.CharField(choices=[('forage', 'Forage'), ('refine', 'Refine'), ('trap', 'Trap Animals'), ('alchemy', 'Alchemy Check')], max_length=20)),
                ('bonus', models.SmallIntegerField()),
                ('applies_to_party', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='items.item')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('item', 'roll_type'), name='unique_modifier_per_roll_type')],
            },
        ),
    ]
