# Generated by Django 5.2.7 on 2026-03-19 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reagents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('item_type', models.CharField(choices=[('arm', 'Arm Slot Item'), ('armor', 'Armor'), ('book', 'Book'), ('feet', 'Feet Slot Item'), ('hand', 'Hand Slot Item'), ('head', 'Head Slot Item'), ('implement', 'Implement'), ('neck', 'Neck Slot Item'), ('ring', 'Ring Slot Item'), ('trap', 'Trap'), ('waist', 'Waist Slot Item'), ('weapon', 'Weapon'), ('wondrous', 'Wondrous Item')], default='wondrous', max_length=20)),
                ('is_two_handed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applies_to_party', models.BooleanField(default=False)),
                ('bonus_value', models.SmallIntegerField()),
                ('roll_type', models.CharField(choices=[('alchemy', 'Alchemy'), ('arcana', 'Arcana'), ('dungeoneering', 'Dungeoneering'), ('history', 'History'), ('insight', 'Insight'), ('nature', 'Nature'), ('perception', 'Perception'), ('trapping', 'Trapping')], max_length=20)),
                ('stacking_rule', models.CharField(choices=[('item_bonus', 'Item Bonus'), ('enhancement_bonus', 'Enhancement Bonus'), ('proficiency_bonus', 'Proficiency Bonus'), ('training_bonus', 'Training Bonus'), ('untyped_bonus', 'Bonus')], default='item_bonus', max_length=20)),
                ('modifier_type', models.CharField(choices=[('flat', 'Flat Modifier'), ('multiplier', 'Roll Multiplier'), ('dice', 'Bonus Dice Roll')], default='flat', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='items.item')),
                ('required_biome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='restricted_modifiers', to='reagents.biome')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('required_biome__isnull', True)), fields=('item', 'roll_type'), name='unique_global_modifier_per_roll_type'), models.UniqueConstraint(condition=models.Q(('required_biome__isnull', False)), fields=('item', 'roll_type', 'required_biome'), name='unique_biome_modifier_per_roll_type')],
            },
        ),
    ]
