# Generated by Django 5.2.7 on 2026-03-17 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('reagents', '0002_alter_biome_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='itemmodifier',
            name='unique_modifier_per_roll_type',
        ),
        migrations.RenameField(
            model_name='itemmodifier',
            old_name='bonus',
            new_name='bonus_value',
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('arm', 'Arm Slot Item'), ('armor', 'Armor'), ('book', 'Book'), ('feet', 'Feet Slot Item'), ('hand', 'Hand Slot Item'), ('head', 'Head Slot Item'), ('neck', 'Neck Slot Item'), ('ring', 'Ring Slot Item'), ('trap', 'Trap'), ('weapon', 'Weapon'), ('wondrous', 'Wondrous Item')], default='wondrous', max_length=20),
        ),
        migrations.AddField(
            model_name='itemmodifier',
            name='modifier_type',
            field=models.CharField(choices=[('flat', 'Flat Modifier'), ('multiplier', 'Roll Multiplier'), ('dice', 'Bonus Dice Roll')], default='flat', max_length=20),
        ),
        migrations.AddField(
            model_name='itemmodifier',
            name='required_biome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='restricted_modifiers', to='reagents.biome'),
        ),
        migrations.AddField(
            model_name='itemmodifier',
            name='stacking_rule',
            field=models.CharField(choices=[('item_bonus', 'Item Bonus'), ('enhancement_bonus', 'Enhancement Bonus'), ('proficiency_bonus', 'Proficiency Bonus'), ('training_bonus', 'Training Bonus'), ('untyped_bonus', 'Bonus')], default='item_bonus', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemmodifier',
            name='roll_type',
            field=models.CharField(choices=[('alchemy', 'Alchemy'), ('arcana', 'Arcana'), ('dungeoneering', 'Dungeoneering'), ('history', 'History'), ('insight', 'Insight'), ('nature', 'Nature'), ('perception', 'Perception'), ('trapping', 'Trapping')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='itemmodifier',
            constraint=models.UniqueConstraint(condition=models.Q(('required_biome__isnull', True)), fields=('item', 'roll_type'), name='unique_global_modifier_per_roll_type'),
        ),
        migrations.AddConstraint(
            model_name='itemmodifier',
            constraint=models.UniqueConstraint(condition=models.Q(('required_biome__isnull', False)), fields=('item', 'roll_type', 'required_biome'), name='unique_biome_modifier_per_roll_type'),
        ),
    ]
