# Generated by Django 5.2.7 on 2026-03-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_itemmodifier_unique_modifier_per_roll_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('arm', 'Arm Slot Item'), ('armor', 'Armor'), ('book', 'Book'), ('feet', 'Feet Slot Item'), ('hand', 'Hand Slot Item'), ('head', 'Head Slot Item'), ('implement', 'Implement'), ('neck', 'Neck Slot Item'), ('ring', 'Ring Slot Item'), ('trap', 'Trap'), ('waist', 'Waist Slot Item'), ('weapon', 'Weapon'), ('wondrous', 'Wondrous Item')], default='wondrous', max_length=20),
        ),
    ]
