# Generated by Django 5.2.7 on 2026-03-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_two_handed',
            field=models.BooleanField(default=False),
        ),
    ]
