# Generated by Django 5.2.7 on 2026-03-31 07:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('characters', '0001_initial'),
        ('items', '0001_initial'),
        ('reagents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('item', 'Item'), ('raw_reagent', 'Raw Reagent'), ('crude_reagent', 'Crude Reagent'), ('refined_reagent', 'Refined Reagent'), ('potion', 'Potion'), ('storgstrum', "Storgstrum's Brew")], db_index=True, max_length=20)),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_entries', to='characters.character')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='item_entry', to='inventory.inventoryentry')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='items.item')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedReagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('crude', 'Crude'), ('refined', 'Refined')], default='crude', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processed_reagent', to='inventory.inventoryentry')),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processed_reagents', to='reagents.reagent')),
            ],
        ),
        migrations.CreateModel(
            name='ReagentSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_description', models.TextField(blank=True, null=True)),
                ('is_mundane', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('found_biome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='found_samples', to='reagents.biome')),
                ('inventory_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sample', to='inventory.inventoryentry')),
                ('source_expedition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='found_samples', to='campaigns.expedition')),
                ('true_reagent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='reagents.reagent')),
            ],
        ),
        migrations.CreateModel(
            name='PotionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_dud_known', models.BooleanField(default=False)),
                ('potency', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discovered_effect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reagents.potioneffect')),
                ('inventory_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='potion_batch', to='inventory.inventoryentry')),
                ('reagent_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uses_in_first_slot', to='reagents.reagent')),
                ('reagent_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uses_in_second_slot', to='reagents.reagent')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('reagent_a', models.F('reagent_b')), _negated=True), name='potion_batch_distinct_reagents')],
            },
        ),
    ]
