# Generated by Django 5.2.7 on 2026-03-19 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_expedition_executed_at'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reagentsample',
            name='source_expedition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='found_samples', to='campaigns.expedition'),
        ),
        migrations.AlterField(
            model_name='inventoryentry',
            name='kind',
            field=models.CharField(choices=[('item', 'Item'), ('raw_reagent', 'Raw Reagent'), ('crude_reagent', 'Crude Reagent'), ('refined_reagent', 'Refined Reagent'), ('potion', 'Potion'), ('storgstrum', "Storgstrum's Brew")], db_index=True, max_length=20),
        ),
    ]
