# Generated by Django 5.2.7 on 2026-04-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reagentsample',
            name='observed_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
