# Generated by Django 5.2.7 on 2026-03-19 06:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('characters', '0003_alter_equippeditem_slot'),
        ('reagents', '0003_alter_biome_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_mode', models.CharField(choices=[('together', 'Together'), ('splitup', 'Split Up')], default='together', max_length=10)),
                ('search_at_night', models.BooleanField(default=False)),
                ('hours', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expeditions', to=settings.AUTH_USER_MODEL)),
                ('biome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expeditions', to='reagents.biome')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expeditions', to='campaigns.campaign')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_expeditions', to='characters.character')),
                ('target_reagent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='targeted_expeditions', to='reagents.reagent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='characters.character')),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='campaigns.expedition')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('character', 'expedition'), name='unique_character_per_expedition')],
            },
        ),
    ]
