# Generated by Django 5.2.7 on 2026-03-19 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('characters', '0001_initial'),
        ('reagents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_expeditions', to='characters.character'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='target_reagent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='targeted_expeditions', to='reagents.reagent'),
        ),
        migrations.AddField(
            model_name='participation',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='characters.character'),
        ),
        migrations.AddField(
            model_name='participation',
            name='expedition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='campaigns.expedition'),
        ),
        migrations.AddConstraint(
            model_name='campaignmembership',
            constraint=models.UniqueConstraint(fields=('user', 'campaign'), name='unique_campaign_membership'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(fields=('character', 'expedition'), name='unique_character_per_expedition'),
        ),
    ]
