# Generated by Django 5.2.7 on 2026-03-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='search_speed',
            field=models.CharField(choices=[('normal', 'Normal Speed'), ('rush', 'Rush Job')], default='normal', max_length=10),
        ),
    ]
