# Generated by Django 5.2.7 on 2026-03-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_expedition_search_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
