# Generated by Django 5.2.7 on 2026-03-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_expedition_executed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
