# Generated by Django 5.2.7 on 2026-03-27 04:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('campaigns', '0005_add_campaign_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.UniqueConstraint(fields=('billing_owner', 'name'), name='unique_campaign_name_per_owner'),
        ),
    ]
