# Generated by Django 5.2.7 on 2026-03-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_add_campaign_ban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('executed', 'Executed')], default='pending', max_length=10),
        ),
    ]
