# Generated by Django 5.2.7 on 2025-12-18 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('upv', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('rpv', models.SmallIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='reagents/')),
            ],
        ),
        migrations.CreateModel(
            name='PotionEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('lvl1', models.CharField(max_length=500)),
                ('lvl2', models.CharField(max_length=500)),
                ('lvl3', models.CharField(max_length=500)),
                ('lvl4', models.CharField(max_length=500)),
                ('lvl5', models.CharField(max_length=500)),
                ('lvl6', models.CharField(max_length=500)),
                ('lvl7', models.CharField(max_length=500)),
                ('lvl8', models.CharField(max_length=500)),
                ('lvl9', models.CharField(max_length=500)),
                ('lvl10', models.CharField(max_length=500)),
                ('reagents', models.ManyToManyField(related_name='potion_effects', to='reagent.reagent')),
            ],
        ),
        migrations.CreateModel(
            name='Biome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('reagents', models.ManyToManyField(related_name='biomes', to='reagent.reagent')),
            ],
        ),
    ]
